"""cambio de la columna calculo

Revision ID: 381017bf1481
Revises: d8b87b5750ae
Create Date: 2025-04-14 19:28:29.444428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381017bf1481'
down_revision = 'd8b87b5750ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoja_vida', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculo', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoja_vida', schema=None) as batch_op:
        batch_op.drop_column('calculo')

    # ### end Alembic commands ###
