"""Cambios generales de la bd del dia 11/4/2025

Revision ID: 3efcdf963eba
Revises: 
Create Date: 2025-04-11 12:15:53.025673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3efcdf963eba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cronograma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actividad', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('fecha_inicio_prog', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('fecha_fin_prog', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('fecha_inicio_real', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('fecha_fin_real', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('avance_planificado', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('desviacion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('indicador_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'indicadores', ['indicador_id'], ['id'])
        batch_op.drop_column('fecha_inicio')
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('hoja_vida', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vigencia_inicio', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('vigencia_fin', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('nivel_generacion', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nivel_util', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('unidad_medida', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('naturaleza', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('definicion', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('indicador_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['indicador_id'])
        batch_op.create_foreign_key(None, 'indicadores', ['indicador_id'], ['id'])
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('indicadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('real_af_antes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('objetivo_af_actual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('año_fiscal', sa.Integer(), nullable=False))
        batch_op.drop_constraint('indicadores_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('indicadores_ibfk_2', type_='foreignkey')
        batch_op.drop_column('version')
        batch_op.drop_column('año')
        batch_op.drop_column('cronograma_id')
        batch_op.drop_column('real_af_prox')
        batch_op.drop_column('objetivo_af_prox')
        batch_op.drop_column('hoja_vida_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('indicadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hoja_vida_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('objetivo_af_prox', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('real_af_prox', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('cronograma_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('año', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('version', mysql.FLOAT(), nullable=True))
        batch_op.create_foreign_key('indicadores_ibfk_2', 'hoja_vida', ['hoja_vida_id'], ['id'])
        batch_op.create_foreign_key('indicadores_ibfk_3', 'cronograma', ['cronograma_id'], ['id'])
        batch_op.drop_column('año_fiscal')
        batch_op.drop_column('objetivo_af_actual')
        batch_op.drop_column('real_af_antes')

    with op.batch_alter_table('hoja_vida', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', mysql.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('indicador_id')
        batch_op.drop_column('definicion')
        batch_op.drop_column('naturaleza')
        batch_op.drop_column('unidad_medida')
        batch_op.drop_column('nivel_util')
        batch_op.drop_column('nivel_generacion')
        batch_op.drop_column('vigencia_fin')
        batch_op.drop_column('vigencia_inicio')

    with op.batch_alter_table('cronograma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('fecha_fin', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('fecha_inicio', mysql.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('indicador_id')
        batch_op.drop_column('desviacion')
        batch_op.drop_column('avance_planificado')
        batch_op.drop_column('fecha_fin_real')
        batch_op.drop_column('fecha_inicio_real')
        batch_op.drop_column('fecha_fin_prog')
        batch_op.drop_column('fecha_inicio_prog')
        batch_op.drop_column('actividad')

    # ### end Alembic commands ###
