"""actualizacion unidad de medida

Revision ID: 497ffa26a61b
Revises: b8f0ecc9c0b6
Create Date: 2025-05-19 19:03:14.787826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '497ffa26a61b'
down_revision = 'b8f0ecc9c0b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoja_vida', schema=None) as batch_op:
        batch_op.alter_column('unidad_medida',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoja_vida', schema=None) as batch_op:
        batch_op.alter_column('unidad_medida',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
