"""Haciendo la gestion de las columnas de estatus

Revision ID: 7a244809d07b
Revises: 381017bf1481
Create Date: 2025-05-02 13:58:40.748363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a244809d07b'
down_revision = '381017bf1481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_aprobacion', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicadores', schema=None) as batch_op:
        batch_op.drop_column('status_aprobacion')

    # ### end Alembic commands ###
