"""habilitacion gdd

Revision ID: b8f0ecc9c0b6
Revises: 9623c1e22c3f
Create Date: 2025-05-07 19:06:37.487745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f0ecc9c0b6'
down_revision = '9623c1e22c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habilitacion_gdd', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('habilitacion_gdd')

    # ### end Alembic commands ###
