"""cambio a Text la columna de calculo de hoja de vida

Revision ID: bd011d581e4d
Revises: 497ffa26a61b
Create Date: 2025-05-20 15:13:43.371582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd011d581e4d'
down_revision = '497ffa26a61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoja_vida', schema=None) as batch_op:
        batch_op.alter_column('calculo',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoja_vida', schema=None) as batch_op:
        batch_op.alter_column('calculo',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
