"""cambio a Text la columna de naturaleza de hoja de vida

Revision ID: c23a9964d0e7
Revises: bd011d581e4d
Create Date: 2025-05-21 13:07:56.671158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c23a9964d0e7'
down_revision = 'bd011d581e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoja_vida', schema=None) as batch_op:
        batch_op.alter_column('naturaleza',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoja_vida', schema=None) as batch_op:
        batch_op.alter_column('naturaleza',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
