"""El JSON en un solo registro

Revision ID: d8b87b5750ae
Revises: 3efcdf963eba
Create Date: 2025-04-14 19:25:20.312419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8b87b5750ae'
down_revision = '3efcdf963eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cronograma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cronograma', sa.Text(), nullable=False))
        batch_op.drop_column('avance_planificado')
        batch_op.drop_column('fecha_inicio_real')
        batch_op.drop_column('actividad')
        batch_op.drop_column('fecha_inicio_prog')
        batch_op.drop_column('fecha_fin_real')
        batch_op.drop_column('fecha_fin_prog')
        batch_op.drop_column('desviacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cronograma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desviacion', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_fin_prog', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('fecha_fin_real', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('fecha_inicio_prog', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('actividad', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('fecha_inicio_real', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('avance_planificado', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('data_cronograma')

    # ### end Alembic commands ###
