"""Creando Tabla de Cargos

Revision ID: dfccd1755d33
Revises: 7a244809d07b
Create Date: 2025-05-06 14:35:21.461021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfccd1755d33'
down_revision = '7a244809d07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargo', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargos', schema=None) as batch_op:
        batch_op.drop_column('cargo')

    # ### end Alembic commands ###
